// flyctl helpers for compute v3.2 source-deploy. Path A — refined:
// the CLI shells out to `flyctl deploy --remote-only --build-only --push`
// using a per-app deploy token minted by the cloud. Build runs on Fly's
// remote builder; the resulting image is pushed straight to registry.fly.io.
// No local Docker daemon required — the user only needs the single flyctl
// binary on their PATH.
//
// Token shape: short-lived (~20 min) macaroon attenuated to one app +
// builder/wg features, with `else: deny`. It can deploy to that one app and
// nothing else, even within the InsForge Fly org.

import { spawn, spawnSync } from 'node:child_process';
import { existsSync, writeFileSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { CLIError } from './errors.js';

export function ensureFlyctlAvailable(): void {
  const r = spawnSync('flyctl', ['version'], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  if (r.error || r.status !== 0) {
    throw new CLIError(
      'flyctl is required for source-mode deploy.\n' +
        '  • Install: curl -L https://fly.io/install.sh | sh\n' +
        '  • Or use --image <pre-built-image> instead.\n' +
        (r.stderr ? `  Detail: ${r.stderr.trim().slice(0, 200)}` : '')
    );
  }
}

export interface FlyctlBuildPushOptions {
  dir: string;
  appId: string; // Fly app name, e.g. "my-svc-<projectId>"
  imageLabel: string; // tag suffix; only used as buildkit's --image-label.
  token: string; // attenuated FlyV1 deploy token from cloud /deploy-token
  region: string; // Fly region — written into the stub fly.toml
  port: number; // container internal port — written into the stub fly.toml
  protocol?: 'http' | 'tcp';
}

/**
 * Write a minimal stub fly.toml in the user's directory so `flyctl deploy
 * --remote-only` has app config. On a freshly-created Fly app with zero
 * machines, flyctl errors with "could not create a fly.toml from any
 * machines" — it tries to derive config from existing machines and there
 * are none yet. The comment claiming "flyctl will invent a fly.toml" was
 * wrong: it does so only if the app already has machines to introspect.
 *
 * If the user already has a fly.toml, leave it alone — they're either
 * customising or driving a non-trivial setup (multi-process, volumes, etc.).
 *
 * Returns a cleanup callback the caller MUST run in a finally block to
 * delete the stub if (and only if) we created it.
 */
function ensureFlyTomlStub(opts: { dir: string; appId: string; region: string; port: number; protocol?: 'http' | 'tcp' }): () => void {
  const path = join(opts.dir, 'fly.toml');
  if (existsSync(path)) {
    return () => {
      /* user owns the file — leave as-is */
    };
  }
  // Default to scale-to-zero (`auto_stop_machines = "stop"`), matching both the
  // cloud Machines-API provisioning path and Fly's own `fly launch` default —
  // idle machines stop instead of billing 24/7. Users who need always-on
  // supply their own fly.toml (the existsSync check above leaves it untouched).
  const serviceBlock =
    opts.protocol === 'tcp'
      ? `[[services]]\n` +
        `  internal_port = ${opts.port}\n` +
        `  protocol = "tcp"\n` +
        `  auto_stop_machines = "stop"\n` +
        `  auto_start_machines = true\n` +
        `  min_machines_running = 0\n` +
        `\n` +
        `  [[services.ports]]\n` +
        `    port = ${opts.port}\n`
      : `[http_service]\n` +
        `  internal_port = ${opts.port}\n` +
        `  force_https = true\n` +
        `  auto_stop_machines = "stop"\n` +
        `  auto_start_machines = true\n` +
        `  min_machines_running = 0\n`;
  const stub =
    `# Auto-generated by @insforge/cli for compute deploy. Safe to delete.\n` +
    `app = "${opts.appId}"\n` +
    `primary_region = "${opts.region}"\n` +
    `\n` +
    `[build]\n` +
    `\n` +
    serviceBlock;
  writeFileSync(path, stub, 'utf8');
  return () => {
    try { unlinkSync(path); } catch { /* best-effort */ }
  };
}

/**
 * Run `flyctl deploy --remote-only --build-only --push` against the user's
 * source directory. Builds on Fly's remote builder, pushes to registry.fly.io,
 * and returns the resulting image ref. Does NOT launch a machine — the cloud
 * backend handles that step (it owns DB state and quota enforcement).
 *
 * IMPORTANT: returns the **digest-pinned** ref `<app>@sha256:<digest>`, not
 * the tag-based `<app>:<label>` ref. buildkit's `--build-only --push` lands
 * the manifest in the remote builder's namespace, and Fly's registry then
 * aliases the user-app namespace to it by content digest. The bare tag does
 * not always resolve (and racily fails on Fly's side as MANIFEST_UNKNOWN),
 * but the digest always does. The cloud's launchMachine accepts either form.
 *
 * If the user's directory has no fly.toml, we write a stub before invoking
 * flyctl and remove it after. flyctl needs the stub on a fresh app with no
 * machines — the comment claiming otherwise was wrong.
 */
export function flyctlBuildAndPush(
  opts: FlyctlBuildPushOptions
): Promise<{ imageRef: string }> {
  return new Promise<{ imageRef: string }>((resolve, reject) => {
    const cleanupStub = ensureFlyTomlStub({
      dir: opts.dir,
      appId: opts.appId,
      region: opts.region,
      port: opts.port,
      protocol: opts.protocol,
    });
    const child = spawn(
      'flyctl',
      [
        'deploy',
        '--remote-only',
        '--build-only',
        '--push',
        '--app',
        opts.appId,
        '--image-label',
        opts.imageLabel,
        '--no-cache',
      ],
      {
        cwd: opts.dir,
        env: { ...process.env, FLY_API_TOKEN: opts.token },
        stdio: ['inherit', 'pipe', 'pipe'],
      }
    );

    // Tee child's stdout+stderr to our own (so the user sees buildkit
    // progress in real time) AND capture them so we can parse the digest.
    let captured = '';
    child.stdout?.on('data', (b) => {
      const s = b.toString();
      captured += s;
      process.stdout.write(s);
    });
    child.stderr?.on('data', (b) => {
      const s = b.toString();
      captured += s;
      process.stderr.write(s);
    });
    child.on('error', (err) => {
      cleanupStub();
      reject(new CLIError(`flyctl deploy could not start: ${err.message}`));
    });
    child.on('exit', (code) => {
      cleanupStub();
      if (code !== 0) {
        return reject(
          new CLIError(`flyctl deploy --build-only failed (exit ${code}). See output above.`)
        );
      }
      // buildkit emits "pushing manifest for registry.fly.io/<app>:<label>@sha256:<digest>"
      // when the upload lands. Pin to that digest so the cloud's machine API
      // can resolve unambiguously regardless of registry tag-aliasing races.
      const m = captured.match(/pushing manifest for registry\.fly\.io\/[^\s]+@(sha256:[0-9a-f]+)/);
      if (!m) {
        return reject(
          new CLIError(
            'flyctl deploy succeeded but the buildkit "pushing manifest" line was not found. ' +
              'Cannot determine image digest — please re-run with FLY_LOG_LEVEL=debug and report.'
          )
        );
      }
      resolve({ imageRef: `registry.fly.io/${opts.appId}@${m[1]}` });
    });
  });
}
